//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        public int id_doc { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public byte[] documento1 { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<System.DateTime> fechar_sumit { get; set; }
        public Nullable<System.DateTime> hora_sumit { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
